# =============================================================================
# ST7305 RLCD Example Configuration
# Waveshare ESP32-S3-RLCD-4.2 (400x300 Reflective LCD)
# =============================================================================
#
# This example demonstrates the ST7305 RLCD driver for ESPHome.
# The reflective LCD requires no backlight and is highly visible in daylight.
#
# Hardware:
#   - Board: Waveshare ESP32-S3-RLCD-4.2
#   - Display: 400x300 1-bit reflective LCD
#   - Controller: ST7305
#
# =============================================================================

esphome:
  name: rlcd-display
  friendly_name: "RLCD Display"

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

# Enable PSRAM for lookup tables (~360KB)
psram:
  mode: octal
  speed: 80MHz

# Logging
logger:
  level: DEBUG

# SPI bus configuration
spi:
  clk_pin: GPIO11
  mosi_pin: GPIO12

# External component
external_components:
  - source: github://kylehase/ESPHome-ST7305-RLCD
    components: [ st7305_rlcd ]
    refresh: 0s

# =============================================================================
# Font Configuration
# =============================================================================
font:
  - file: "gfonts://Roboto"
    id: roboto
    size: 40

# =============================================================================
# Display Configuration
# =============================================================================
display:
  - platform: st7305_rlcd
    model: WAVESHARE_400X300
    rotation: 0
    id: my_display
    cs_pin: GPIO40
    dc_pin: GPIO5
    reset_pin: GPIO41
    update_interval: never
    
    lambda: |-
      // Get dimensions
      int w = it.get_width();
      int h = it.get_height();

      // Print "Hello World!" in the center of the screen
      // Arguments: x, y, font_id, color, alignment, text
      it.printf(w / 2, h / 2, id(roboto), COLOR_ON, TextAlign::CENTER, "Hello World!");
      id(my_display).low_power_mode();